### ISSUE TITLE
Add notifications via telegram or some other channel

### ISSUE THREAD

**Issue by nombrekeff** [nombrekeff/better-issues#13]
Maybe users could configure how they would like to get notified, something like:
```yaml
notifications:
    default_message: > 
        Hi, I'm wallas, this is an automated notification!
    channels: 
        - telegram
        - issues
        - mail
    env:
        telegram_token: <bot_token>

on_push:
    - match: 
          branch: master
      do: 
        - notify: 
            channel: telegram
            message: A new push to master was performed by: @{payload.sender.login}
            

```
