### ISSUE TITLE
Github actions must allow performing actions on all entries and filtered

### ISSUE THREAD

**Issue by nombrekeff** [nombrekeff/better-issues#17]
For example, this will close all issues containing label `closes-in:{tag_name}`
```yml
on_push:
  - match: 
      ref: tag
    do:
       - close: 
           what: issue
           label: 
               matching:  closes-in:{payload.ref.tag}


```
