### ISSUE TITLE
Filters should be more flexible and allow more types of checks

### ISSUE THREAD

**Issue by nombrekeff** [nombrekeff/better-issues#18]
Now matchers only check a value, it would be nice to be more flexible in the way you check stuff, for example maybe you want to check if a branch is one of x values, for that you could do:
```yml
on_push:
  - check:
      branch:
          one_of: [master, stable, windows]
    do: 
```

List of filtering options:
* `is` - must match **exactly** that value
* `contains` - must **contain** that value
* `one_of` - check if it matches **at least one** value
* `none_of` - check if it does not **match neither** of the values
* `pattern` - check agains a regular expresion
